<?php
$music = array(
  array(
    "title" => "Motown / Northern Soul / Stax / Atlantic",
    "about" => "All the classic Tamla Motown hits, RnB, Wigan Casino classics and sweet soul ballads. We can cater to those who were at the Twisted Wheel the first time around or to those who just want to hear the upfront hits.\n\nThis set leans towards the hits, but with a few that you may have heard at Blackpool Mecca back in the day.",
    "playlist" => array(
      "Diana Ross - You Can't Hurry Love",
      "Four Tops - Something About You",
      "Martha Reeves and The Vandellas - Jimmy Mack",
      "Marvin Gaye - I Heard It Through The Grapevine",
      "Stevie Wonder - Uptight (Everything's Alright)",
      "Otis Redding - Satisfaction",
      "Smokey Robinson - Tears Of A Clown",
      "Isley Brothers - This Old Heart Of Mine",
      "Temptations - Ain't Too Proud to Beg",
      "Jnr Walker and The All Stars - Shotgun",
      "Edwin Starr - 25 Miles",
      "Gloria Jones - Tainted Love",
      "Ray Charles - What'd I Say",
      "Dobie Gray - Out On The Floor",
      "Jackie Wilson - Higher and Higher",
      "Curtis Mayfield - Move On Up",
      "Candi Staton - Young Hearts Run Free",
      "Sam and Dave - Soul Man",
      "Frank Wilson - Do I Love You (Indeed I Do)",
      "The Elgins - Heaven Must Have Sent You",
      "Velvelettes - Needle In A Haystack",
      "Contours - Do You Love Me",
      "The Dells - Run For Cover",
      "Al Green - Tired Of Being Alone",
      "Arthur Conley - Sweet Soul Music"
    )
  ),
  array(
    "title" => "90's Revival: the trainspotting generation",
    "about" => "Britpop, big beat, drum and bass, hip hop, old skool and rave. Yes, the nineties revival is here! In recent years this type of set has been very popular at weddings and birthday parties.",
    "playlist" => array(
      "Primal Scream - Movin' On Up",
      "Leftfield - Open Up",
      "Chemical Brothers - Block Rockin' Beats",
      "Massive Attack - Unfinished Sympathy",
      "Groove Armada - Superstylin'",
      "Fatboy Slim - Rockafeller Skank",
      "Orbital - Chime",
      "Underworld - Born Slippy",
      "Blur - Parklife",
      "Goldie - Inner City Life",
      "Moby - Why Does My Heart Feel So Bad",
      "Prodigy - Outer Space",
      "SL2 - On A Ragga Tip",
      "St. Etienne - Only Love Can Break Your Heart",
      "Shamen - Move Any Mountain",
      "Pulp - Do You Remember The First Time?",
      "Charlatans - You're So Pretty, We're So Pretty",
      "Bjork - Big Time Sensuality",
      "Deee-lite - Groove Is In The Heart",
      "Basement Jaxx - Bingo Bango",
      "DJ Zinc - Super Sharp Shooter",
      "Roni Size - Brown Paper Bag",
      "Pharcyde - Ya Mama",
      "Vanilla Ice - Ice Ice Baby",
      "MC Hammer - U Can't Touch This"
    )
  ),
  array(
    "title" => "Speakeasy",
    "about" => "Prohibition era swing jazz, lindy hop, jump blues, jitterbug and electro-swing.\n\nEverything from the era of big band swing, right up to the birth of rock and roll. This type of set can work well as a theme for a whole evening or as a mood setter before a more updated set later.",
    "playlist" => array(
      "Louis Jordan - Is You Is, Or Is You Ain't My Baby",
      "Brian Setzer Orchestra - Jump, Jive and Wail",
      "Glenn Miller - In the Mood",
      "Ben Webster - Palm Springs Jump",
      "Duke Ellington - Take the A Train",
      "Frank Sinatra and Dean Martin - Mack The Knife",
      "Sammy Davis Jnr - All That Jazz",
      "Peggy Lee - Fever",
      "Billie Holiday - Swing Brother Swing",
      "Tape Five - Geraldine's Routine",
      "Bobby Darin - Beyond The Sea",
      "Caro Emerald - That Man",
      "Dinah Washington - Mad About The Boy",
      "Discotizer - Stoolies Revenge",
      "Bottle To The Baby - Charlie Feathers",
      "Louis Armstrong - Ain't Misbehavin",
      "Fats Domino - I'm Walkin",
      "Emeli Sande and the Brian Ferry Orchestra - Crazy In Love",
      "Art Tatum - Liza",
      "Jummy Lunceford Orchestra - It Ain't What You Do Its The Way That You Do It",
      "Gramophonedzie - Why Don't You",
      "Yolanda Be Cool - We No Speak Americano",
      "Moloko - Sing It Back (Can 7 1930's Mix)",
      "Eddie Bond - Rockin Daddy",
      "Professor Longhair - Tipitina"
    )
  ),
  array(
    "title" => "80s",
    "about" => "This selection leans heavily in the direction of popular 80's electro pop, with a few more eclectic tracks added for the connoisseurs. This could be made more funk/soul, alternative or rock based by changing the emphasis.",
    "playlist" => array(
      "Gary Numan - Are Friends Electric",
      "Human League - Fascination",
      "Kraftwerk - Computer Love",
      "Kim Wilde - Kids In America",
      "Kid Creole and The Coconuts - Annie, I'm Not Your Daddy",
      "Pigbag - Papa's Got A Brand New Pigbag",
      "New Order - Temptation",
      "Orange Juice - Rip It Up",
      "Deacon Blue - Real Gone Kid",
      "Blondie Denis",
      "Visage - Fade To Grey",
      "Dead Or Alive - You Spin Me Round",
      "Falco - Rock Me Amadeus",
      "Madonna - Holiday",
      "Bronski Beat - Smalltown Boy",
      "OMD - Enola Gay",
      "Pet Shop Boys - West End Girls",
      "Depeche Mode - Just Can't Get Enough",
      "Talking Heads - Once In A Lifetime",
      "Eurythmics - Sweet Dreams",
      "Yazoo - Situation",
      "Fine Young Cannibals - Good Thing",
      "The Beat - Mirror In The Bathroom",
      "Michael Jackson - Thriller",
      "Propaganda - Duel"
    )
  ),
  array(
    "title" => "Disco",
    "about" => "Disco classics from the 70's and 80's. Including Motown Disco, Philly Groove, Loft and Paradise Garage floorfillers, Hi-Energy and underground disco edits. We can make the set a Boogie Nights party with all the well known hits, or cut to the underground with the sort of edits that Dimitri from Paris or Moodymann spin.",
    "playlist" => array(
      "Michael Jackson - Dont Stop Till You Get Enough",
      "Sister Sledge - Lost In Music",
      "Chic - I Want Your Love",
      "Stevie Wonder - Sir Duke",
      "Donna Summer - I Feel Love",
      "Randy Crawford - Street Life",
      "Diana Ross - Love Hangover",
      "Salsoul Orchestra - Runaway",
      "Chaka Khan - Ain't Nobody",
      "Labelle - Lady Marmalade",
      "Double Exposure - Everyman",
      "Sister Sledge - We Are Family",
      "Trampps - Disco Inferno",
      "Jacksons - Blame It On The Boogie",
      "Harold Melvin and the Bluenotes - Don't Leave Me This Way",
      "Roy Ayers - Running Away",
      "Kool and the Gang - Celebration",
      "Lamont Dozier - Going Back To My Roots",
      "Barry White - You're The First, The Last, My Everything",
      "MFSB - Love is the Message",
      "Heatwave - Boogie Nights",
      "Lipps Inc - Funkytown",
      "Average White Band - Pick Up The Pieces",
      "Hamilton Bohannon - Me and The Gang",
      "Dells - No Way Back"
    )
  ),
  array(
    "title" => "Urban: RnB, Hip-Hop, Garage",
    "about" => "RnB, Hip-Hop, Street Soul. We can mix up some classics, underground and mainstream add a bit of dancehall, garage, trap, grime and afrobeats.",
    "playlist" => array(
      "Childish Gambino - Redbone",
      "Gyptian - Hold Yuh",
      "Black Eyed Peas - Boom Boom Pow",
      "Blackstreet - No Diggity",
      "Christina Aguilera Ft Redman - Dirrty",
      "Beyonce - Drunk In Love",
      "Jessie Ware - Midnight",
      "En Vogue - My Lovin'",
      "SZA - The Weekend",
      "Jay-Z & Kanye West - N@@@as In Paris",
      "Jennifer Lopez - Jenny From The Block",
      "Kanye West - Gold Digger",
      "J Hus - Did You See",
      "Kendrick Lamar - Humble",
      "Miguel - Told You So",
      "Fuse ODG - Million Pound Girl",
      "Mr Vegas - Heads High",
      "Ginuwine - Pony",
      "MC Lyte Ft Missy Elliot - Cold Rock A Party",
      "Montell Jordan - This Is How We Do It",
      "N.E.R.D - You Know What",
      "Sean Paul - She Doesn't Mind",
      "ODB - Got Your Money",
      "Pitbull - I Know You Want Me",
      "Biggie Smalls ft Jagged Edge - Nasty Girl"
    )
  ),
  array(
    "title" => "Ibiza : Vocal House Classics",
    "about" => "Classic late 80's / early 90's vocal house, MAW productions, Hed Kandi, Defected, Trance, Garage, Funky House, Deep House, Tech House and Disco House can all be catered for.",
    "playlist" => array(
      "Tori Amos - Professional Widow (Armand Van Helden Mix)",
      "Energy 52 - Cafe Del Mar",
      "Armand Van Heldon - I Want Your Soul",
      "Baby D - Let Me Be Your Fantasy",
      "Bob Sinclar Ft Cutee B - Rock This Party",
      "Cee Cee Peniston - Finally",
      "Clivilles and Cole - A Deeper Love",
      "David Guetta - Just A Little More Love",
      "De'Lacy - Hideaway",
      "DJ Flavors - Your Caress",
      "Incognito - Always There (David Morales Mix)",
      "Kym Sims - Too Blind To See It",
      "Darude - Sandstorm",
      "N-Joi - Anthem",
      "Basement Jaxx - Red Alert",
      "Sandy B - Make The World Go Round",
      "Sterling Void - It's Alright",
      "Axwell - I Found U",
      "Deadmau5 - I Remember",
      "Faithless - Insomnia",
      "Inner City - Big Fun",
      "Crystal Waters - Gypsy Woman",
      "Moloko - Sing It Back",
      "Ten City - Devotion",
      "Deep Dish - Flashdance"
    )
  ),
  array(
    "title" => "Disco 3000: Indie/Rock",
    "about" => "DJ set of classic indie disco songs from the eighties to present day",
    "playlist" => array(
      "Oasis - Supersonic",
      "Supergrass - Alright",
      "Franz Ferdinand - Matinee",
      "Arctic Monkeys - I Bet You Look Good On The Dancefloor",
      "Pixies - Debaser",
      "White Stripes - Seven Nation Army",
      "Pulp - Common People",
      "Strokes - Last Nite",
      "Kasabian - Fire",
      "LCD Soundsystem - Daft Punk is Playing in my House",
      "Killers - Spaceman",
      "Muse - Supermassive Black Hole",
      "Two Door Cinema Club - Something Good Can Work",
      "Libertines - Can't Stand Me Now",
      "Queens of the Stone Age - the Lost Art of Keeping a Secret",
      "Wedding Present - Kennedy",
      "Nirvana - Come As You Are",
      "Primal Scream - Rocks",
      "Charlatans - Tellin' Stories",
      "Blur - Song 2",
      "Happy Mondays - Kinky Afro",
      "Temper Trap - Sweet Disposition",
      "The Cure - Close To Me",
      "Modest Mouse - Lampshades on Fire",
      "The Clash - Rock The Casbah"
    )
  ),
  array(
    "title" => "Rock 'n' Roll",
    "about" => "We can stick to the classic 50's / 60's period, add a bit of rockabilly and jump blues if required, or we can take it up to the present day with tracks influenced by the sounds of Chuck Berry, Bo Diddley and Co., like the list here.",
    "playlist" => array(
      "Big Joe Turner - Shake, Rattle and Roll",
      "Bill Haley - Rock Around the Clock",
      "Chuck Berry - Johnny B Goode",
      "Eddie Cochran - C'mon Erverybody",
      "Elvis Presley - Blue Suede Shoes",
      "Gene Vincent - Rollin' Danny",
      "Jerry Lee Lewis - Whole Lotta Shaking Going On",
      "Johnny Cash - Jackson",
      "Little Richard - Tutti Frutti",
      "Ray Charles - Mess Around",
      "Rolling Stones - Come On",
      "Roy Orbison - Pretty Woman",
      "Beatles - Get Back",
      "Jim Jones Revue - Big Hunk O'Love",
      "Jerry Keller - Here Comes Summer",
      "Monkees - Mary Mary",
      "Bill Haley - Mambo Rock",
      "Stray Cats - Stray Cat Strut",
      "Richie Valens - La Bamba",
      "Clash - Should I Stay Or Should I Go?",
      "Ramones - Needles and Pins",
      "Iggy Pop - Wild One",
      "Fats Domino - Chanilly Lace",
      "Wanda Jackson - Fujiyama Mama",
      "Dion - Runaround Sue"
    )
  ),
  array(
    "title" => "Mods and Rockers",
    "about" => "Quadrophenia relived with sixties mod and RnB, Tamla Motown, northern soul, britpop and rock and roll.\n\nWhether you want to stick to the authentic early/mid sixties period or extend to the seventies revival and britpop the choice is yours.\n\nThis brief set list adds a bit of everything mod related, plus a few for the rockers too.",
    "playlist" => array(
      "The Who - My Generation",
      "Small Faces - Sha-La-La-La-Lee",
      "Kinks - You Really Got Me",
      "Martha Reeves and The Vandellas - Nowhere To Run",
      "The Supremes - Reflections",
      "Four Tops - Its the Same Old Song",
      "Spencer Davis Group - Gimme Some Lovin'",
      "Beatles - Paperback Writer",
      "Rolling Stones - Under My Thumb",
      "Al Wilson - The Snake",
      "Carnaby - Jump and Dance",
      "Brian Auger / Julie Driscoll - Indian Rope Man",
      "Gene Vincent - Be Bop A Lula",
      "Bobby Fuller - I Fought The Law",
      "Led Zeppelin - Rock and Roll",
      "Del Shannon - Runaway",
      "Eddie Cochran - Summertime Blues",
      "The Jam - Town Called Malice",
      "The Police - So Lonely",
      "Clash - London Calling",
      "Style Council - Walls Come Tumbling Down",
      "Ramones - Baby I Love You",
      "Blur - Girls and Boys",
      "Bluetones - Slight Return",
      "Ocean Colour Scene - Hundred Mile High City"
    )
  ),
  array(
    "title" => "Rock Out - Classic Rock",
    "about" => "60's, 70's and 80's Classic Rock, AOR, Glam, Hair Rock, NWOBHM, Blues and Prog. Air guitars at the ready! The set list below plays it hard but with a bit of irony too!",
    "playlist" => array(
      "Foreigner - Cold As Ice",
      "AC/DC - You Shook Me All Night Long",
      "Guns 'N Roses - Sweet Child O' Mine",
      "Thin Lizzy - The Boys Are Back In Town",
      "Black Crowes - Hard To Handle",
      "Aerosmith - Pink",
      "Kiss - God Gave Rock 'N Roll To You",
      "ZZ Top - Sharp Dressed Man",
      "Def Leppard - Pour Some Sugar on Me",
      "Queen - Bohemian Rhapsody",
      "Judas Priest - Breaking the Law",
      "Status Quo - Down Down",
      "Iron Maiden - Run To The Hills",
      "Cult - She Sells Sanctuary",
      "Dire Straits - Sultans of Swing",
      "Rainbow - Since You've Been Gone",
      "Black Sabbath - Paranoid",
      "Led Zeppelin - Rock 'n' Roll",
      "Bon Jovi - Livin' On A Prayer",
      "Jimi Hendrix - Voodoo Child (Slight Return)",
      "Fleetwood Mac - the Chain",
      "Joan Jett and The Blackhearts - I Love Rock and Roll",
      "Creedence Clearwater Revival - Proud Mary",
      "Poison - Ride The Wind",
      "Lynyrd Skynyrd - Freebird"
    )
  ),
  array(
    "title" => "Funk",
    "about" => "Classic funk from the 70's through to present day.\n\nAll eras of funk, from the Godfather of Soul through to present day Daptone type tunes, as played by Craig Charles.",
    "playlist" => array(
      "Sly and the Family Stone - If You Want Me To Stay",
      "James Brown - Talking Loud and Saying Nothing",
      "Tom Browne - Funkin'For Jamaica",
      "Stevie Wonder - Higher Ground",
      "Spanky Wilson - Sunshine Of Your Love",
      "Doris - Don't",
      "Peggy Lee - Sitting On the Dock of the Bay",
      "Patti Drew - Hard to Handle",
      "Parliament - Flashlight",
      "Osibisa - Sunshine Day",
      "Ohio Players - Love Rollercoaster",
      "Nina Simone - Save Me",
      "The Mowhawks - Champ",
      "Marva Whitney - Unwind Yourself",
      "Maceo and the Macks - Cross the Track",
      "Lyn Collins - Do Your Thing",
      "Kool and the Gang - Jungle Boogie",
      "Jean Knight - Mr Big Stuff",
      "Haggis Horns - The Traveller",
      "Gil Scott Heron - The Bottle",
      "The Bongolian - The Riviera Affair",
      "The Third Degree - Can't Get You Out of My Head (Smoove Remix)",
      "Cameo - Candy",
      "Prince Gett Off",
      "War - Me and my Baby Brother"
    )
  ),
  array(
    "title" => "Reggae, Dub, Ska, Rocksteady, 2-Tone, Dancehall and Soca",
    "about" => "All eras of reggae from Studio One / Treasure Isle period through to Greensleeves and present day.",
    "playlist" => array(
      "Prince Buster - Madness",
      "Junior Murvin - Police and Thieves",
      "Lee Perry - Tighten Up",
      "Toots and The Maytals - Monkey Man",
      "Vin Gordon - Magnum Force",
      "Althea and Donna - Uptown Top Rankin",
      "Bob Marley - Could You Be Loved",
      "Max Romeo - Chase The Devil",
      "Steel Pulse - Handsworth Revolution",
      "Selecter - On My Radio",
      "Specials - Ghost Town",
      "Dawn Penn - No, No, No",
      "Dandy Livingstone - A Message to You Rudy",
      "Damian Marley - Welcome to Jamrock",
      "Sister Nancy - Bam Bam",
      "Super Cat - Ghetto Red Hot (Hip Hop Mix)",
      "Gregory Isaacs - Night Nurse",
      "Mr Vegas - Heads High",
      "Yellowman - Hit the Road jack",
      "Gyptian - Hold Yuh (Soca mix)",
      "Sean Paul - I'm Still In Love with You",
      "Chaka Demus - Murder She Wrote",
      "Sneakbo - Ring A Ling",
      "Barrington Levi - Under Mi Sensi",
      "Wayne Smith - Under Mi Sleng Teng"
    )
  ),
  array(
    "title" => "Soul Weekender",
    "about" => "A popular genre at bar nights up and down the country at the moment. The smoother end of seventies Philly, 80's soul, garage, rare groove, modern soul, neo soul and nu jazz.",
    "playlist" => array(
      "Womack and Womack - Teardrops",
      "Barry White - Your Sweetness Is My Weakness",
      "Chaka Khan - Ain't Nobody",
      "D Train - You're The One For Me",
      "Drizabone - Pressure",
      "Oliver Cheatham - Get Down Saturday Night",
      "George Benson - Never Give Up On A Good Thing",
      "Inner Life Ft Jocelyn Brown - Ain't No Mountain High Enough",
      "Chaka Khan - Ain't Nobody",
      "Nuyorican Soul - I Am the Black Gold of the Sun",
      "Jocelyn Brown - Somebody Else's Guy",
      "Kirk Whalum - All I Do",
      "Lauren Hill - Every Ghetto Every City",
      "Luther Vandross - Never Too Much",
      "Marvin Gaye - Got To Give It Up",
      "Nu Shooz - I Can't Wait",
      "Erykah Badu - Honey",
      "Odyssey - Inside Out",
      "Patrice Rushen - Forget Me Nots",
      "Players Association - Turn The Music Up",
      "Rockers Revenge - Walking On Sunshine",
      "Shalamar - Right In The Socket",
      "Soul II Soul - Back To Life",
      "Whispers - One For The Money",
      "Yarborough and Peoples - Don't Stop The Music"
    )
  ),
  array(
    "title" => "Breakdance",
    "about" => "Classic old skool hip hop, seventies funk breaks.\n\nIf you need someone to scratch up those 70's funk beats we've got a couple of DJs who can do that for you in the style of DJ Yoda.",
    "playlist" => array(
      "Sugarhill Gang - Rapper's Delight",
      "Grandmaster Flash - White Lines",
      "Sugar Bear - Don't Scandalize Mine",
      "Babe Ruth - The Mexican",
      "Run DMC - Its Tricky",
      "Pharcyde - Ya Mama",
      "Salt N Pepa - Push It",
      "DJ Format - Music For the Mature B-Boy",
      "Chubb Rock - Treat 'Em Right",
      "James Brown - Talking Loud and Saying Nothing",
      "Skee-Lo - I Wish",
      "NWA - Express Yourself",
      "Nextmen - Round Of Applause",
      "Mark Ronson - Ooh Wee",
      "Lizzo - Batches and Cookies",
      "Jurrassic 5 - Jayou",
      "Rick James - Superfreak",
      "Ice Cube - U Can Do It",
      "Eric B and Rakim - You Know I Got Soul",
      "De La Soul - Ring Ring Ring",
      "Breakestra - Family Rap",
      "Digital Underground - The Humpty Dance",
      "DJ Yoda ft Scroobius Pip - Sega RIP",
      "EPMD - Strictly Business",
      "MC Lyte - Cold Rock a Party"
    )
  ),
  array(
    "title" => "Madchester and the Hacienda",
    "about" => "Tony Wilson may have passed on but his memory can be kept alive at your party! A mixture of Manchester baggy tunes, chicago house and old skool classics. Even if you never made it through the doors, if you're of a certain age these tunes will resonate in a way no others will.",
    "playlist" => array(
      "Happy Mondays - Hallelujah",
      "New Order - Blue Monday",
      "Charlatans - The Only One I Know",
      "The Fall - Hit The North",
      "Joy Division - Love Will Tear Us Apart",
      "The Smiths - Bigmouth Strikes Again",
      "Stone Roses - Fools Gold",
      "James - Come Home",
      "808 State - Pacific State",
      "K-Klass - Rhythm Is A Mystery",
      "Marshall Jefferson - Move Your Body",
      "Candi Staton - You Got The Love",
      "A Guy Called Gerald - Voodoo Ray",
      "Primal Scream - Loaded",
      "Al Naayfish - Hashim",
      "Bassheads - Is There Anybody Out There",
      "Alison Limerick - Where Love Lies",
      "Inspiral Carpets - Saturn 5",
      "The La's - There She Goes",
      "Flowered Up - Weekender",
      "Electronic - Get The Message",
      "Chemical Brothers - Song To The Siren",
      "ESG - You're No Good",
      "Soup Dragons - I'm Free",
      "Quando Quango - Love Tempo"
    )
  ),
  array(
    "title" => "Pop, RnB, Dance and Chart Hits",
    "about" => "We always have the latest chart music.",
    "playlist" => array(
      "Eminem ft Ed Sheeran - River",
      "Daft Punk ft Pharell - Get Lucky",
      "Beyonce - Drunk in Love",
      "Clean Bandit - Miss You",
      "Major Lazer and DJ Snake - Lean On",
      "Big Shaq - Man's Not Hot",
      "Taylor Swift - Shake It Off",
      "Camila Cabello ft Young Thug - Havana",
      "Jax Jones - Breath",
      "Selina Gomez ft Marshmello - Wolves",
      "J Hus - Bouff Daddy",
      "Luis Fonsi / Daddy Yankee / Bieber - Despacito",
      "Ed Sheeran - Shape of You",
      "French Montana ft Swae Lee - Unforgettable",
      "Pharell Williams - Happy",
      "DJ Khaled ft Rihanna - Wild Thoughts",
      "Jason Derulo - Swalla",
      "Post Malone ft 21 Savage - Rockstar",
      "Macklemore and Lewis - Thrift Shop",
      "Mark Ronson - Uptown Funk",
      "Shawn Mendes - There's Nothing Holding me Back",
      "Clean Bandit ft Shaun Paul - Rockabye",
      "Little Mix - Touch",
      "Charlie Puth - Attention",
      "Bruno Mars - 24k"
    )
  ),
  array(
    "title" => "Elektronik Rock - Electro Disco",
    "about" => "Indie / alternative meets electro. Electroclash, Punk Funk, 2 Many DJs, Ghettotech, Electro House, Digital Rock, Kitsune Maison....",
    "playlist" => array(
      "White Stripes - Seven Nation Army - Adam Freeland Mix",
      "MGMT - Kids (Soulwax Nite Version)",
      "Gossip - Standing In The Way Of Control",
      "Yo Mama - Club Action",
      "Riton vs Primary - Radiates",
      "Rapture - House Of Jealous Lovers",
      "Mylo - Destroy Rock And Roll (Riton Rerub)",
      "Hot Chip - One Life Stand",
      "Chemical Brothers - Do It Again",
      "Architecture In Helsinki - Do The Whirlwind (Hot Chip Remix)",
      "Yeah Yeah Yeahs - Heads Will Roll (A-Trak Remix)",
      "!!! - Must Be The Moon",
      "TV On The Radio - Wolf Like Me",
      "Soulwax - Another Excuse (DFA Remix)",
      "Klein & MBO - Dirty Talk",
      "LCD Soundsystem - Disco Infiltrator",
      "The Horrors - Sea Within A Sea",
      "Friendly Fires - Skeleton Boy",
      "Delphic - Couterpoint",
      "CSS - Lets Make Love & Listen To Death From Above",
      "Animal Collective - My Girls",
      "Gorillaz - Dare (DFA mix)",
      "Beck - Where It's At",
      "Tom Vek - Nothing But Green Lights",
      "Terranova - Good Bye The Ferrari"
    )
  ),
  array(
    "title" => "Download - modern heavy rock",
    "about" => "Pretty much everything from Metallica on to the present day. The music you hear at rock festivals. Metal, Ska Punk, Thrash, Grunge, Emo, Industrial and Goth.",
    "playlist" => array(
      "System of a Down - Chop Suey",
      "Metallica - Creeping Death",
      "Killswitch Engage - Holy Diver",
      "Slipknot - Duality",
      "Foo Fighters - the Pretender",
      "Rob Zombie - Dragula",
      "Linkin Park - Papercut",
      "Sum 41 - In Too Deep",
      "Rammstein - Du Hast",
      "Less Than Jake - All My Best Mates Are Metalheads",
      "Smashing Pumpkins - Bullet With Butterfly Wings",
      "Red Hot Chili Peppers - Can't Stop",
      "Pantera - Cowboys from Hell",
      "Nirvana - Lithium",
      "Ministry - Jesus Built My Hotrod",
      "Marilyn Manson - Mechanical Animals",
      "Korn - Freak on a Leash",
      "Limp Bizkit - Rollin'",
      "Disturbed - Down with the Sickness",
      "Rage Against the Machine - Killing in the Name",
      "Blink 182 - All the Small Things",
      "Biffy Clyro - Bubbles",
      "Anthrax - Antisocial",
      "Megadeth - Peace Sells",
      "Skindred - Rat Race"
    )
  ),
  array(
    "title" => "House / Techno",
    "about" => "Electronic classics from Chicago, Detroit and Europe. Techno might not be everyone's cup of tea, but the list here shows how we could combine its funkier elements with some classic vocal house tracks to keep the dance floor open to all.",
    "playlist" => array(
      "Inner City - Good Life",
      "Candi Staton - You Got The Love",
      "Marshall Jefferson - Move Your Body",
      "A Guy Called Gerald - Voodoo Ray",
      "Frankie Knuckles - Baby Wants To Ride",
      "Jeff Mills - The Bells",
      "Derrick May - Strings Of Life",
      "Laurent Garnier - The Man With The Red Face",
      "Masters At Work - To Be In Love",
      "DJ Sneak - U Can't Hide From Your Bud",
      "Todd Terry - Back To The Beat",
      "Adonis - No Way Back",
      "Farley Jackmaster Funk - Love Can't Turn Around",
      "Norma Jean Bell - I'm The Baddest Bitch",
      "Gusto - Disco's Revenge",
      "Joe Smooth - Promised Land",
      "Bizarre Inc - Playing With Knives",
      "Moodymann - Shades Of Jae",
      "Bucketheads - The Bomb!",
      "Daft Punk - Da Funk",
      "Kraftwerk - The Robots",
      "Jam and Spoon - The Age Of Love",
      "Ce Ce Pensiton - Finally",
      "Sueno Latino - Sueno Latino",
      "Lil' Louis - French Kiss"
    )
  )
);

// Clear existing music themes
$existing = get_posts(['post_type' => 'music-theme', 'posts_per_page' => -1, 'fields' => 'ids']);
foreach ($existing as $id) {
    wp_delete_post($id, true);
}
echo "Cleared existing music themes\n";

foreach ( $music as $theme ) {
    $post_id = wp_insert_post([
        'post_title'   => $theme['title'],
        'post_content' => $theme['about'],
        'post_type'    => 'music-theme',
        'post_status'  => 'publish',
    ]);

    if ( $post_id && ! is_wp_error($post_id) ) {
        // Build playlist repeater rows
        $playlist_rows = [];
        foreach ( $theme['playlist'] as $track ) {
            $playlist_rows[] = ['track' => $track];
        }
        update_field('theme_playlist', $playlist_rows, $post_id);

        echo "Created: " . $theme['title'] . " (ID: $post_id)\n";
    } else {
        echo "Failed: " . $theme['title'] . "\n";
    }
}

echo "Done!\n";